### ISSUE TITLE
No current Transparency reports

### ISSUE THREAD

**Issue by dcharles525** [Tox/Tox-Foundation-Discussion#4]
There hasn't been a transparency report since November. Maybe get that up to speed? Looks really sketchy.

**Comment by stqism** [comment]
I updated the site to reflect the current state of things.

Note that it'll take up to 4 hours to roll out.

![screen shot 2015-03-24 at 11 12 58 am](https://cloud.githubusercontent.com/assets/2031258/6809464/b965c9f6-d217-11e4-8324-f84669ed2f8a.png)

**Comment by dcharles525** [comment]
@stqism Thank you for quick fix and your continued dedication to Tox.
